name = "my-sentiment-service"
main = "dist/index.js"
compatibility_date = "2025-01-01"

# Uncomment if you're using KV or D1
# kv_namespaces = [
#   { binding = "MY_KV", id = "xxxxxx" }
# ]
# d1_databases = [
#   { binding = "MY_D1", database_id = "xxxxxx" }
# ]
